export interface PhraseEntry {
  readonly phrase: string
  readonly replacement?: string
}

export const fillers: readonly string[] = [
  'basically',
  'literally',
  'you know',
  'i mean',
  'just',
  'actually',
  'honestly',
  'obviously',
  'clearly',
  'right',
]

export const hedges: readonly string[] = [
  'kind of',
  'sort of',
  'a little bit',
  'maybe',
  'i think',
  'i feel like',
  'i guess',
  'perhaps',
  'somewhat',
  'slightly',
]

export const intensifiers: readonly string[] = [
  'very',
  'really',
  'extremely',
  'incredibly',
  'absolutely',
  'totally',
  'completely',
  'truly',
  'highly',
  'utterly',
]

export const redundantPairs: readonly string[] = [
  'absolutely essential',
  'completely finished',
  'very unique',
  'end result',
  'free gift',
  'past history',
  'future plans',
  'each and every',
  'first and foremost',
]

export const weaselAttribution: readonly string[] = [
  'some people say',
  'studies show',
  'experts agree',
  'research suggests',
]

export const selfAttribution: readonly string[] = [
  'i believe that',
  'in my opinion',
  'personally i think',
  'from my perspective',
]

export const credibilityKillers: readonly string[] = [
  'does that make sense',
  'if that makes sense',
]

export const weakClosers: readonly string[] = [
  'so yeah',
  'and stuff like that',
  'and whatnot',
  'you get the idea',
]

export const apologeticPreambles: readonly string[] = [
  'sorry but',
  'this might be wrong but',
  "i'm no expert but",
  "i'm not sure if this is right but",
]

export const throatClearing: readonly string[] = [
  "it's important to note that",
  'the fact of the matter is',
  'it goes without saying',
  'let me start by saying',
  'it should be noted that',
  'it is worth mentioning that',
  'needless to say',
  'as a matter of fact',
  'at the end of the day',
  'the bottom line is',
]

export const existenceStarters: readonly string[] = [
  'there is',
  'there are',
  'there was',
  'there will be',
]

export const frontLoadedNegatives: readonly string[] = [
  "i'm not sure",
  "i don't know if",
  "i can't say for certain",
]

export const wordyPhrases: readonly PhraseEntry[] = [
  { phrase: 'in order to', replacement: 'to' },
  { phrase: 'the reason being is', replacement: 'because' },
  { phrase: 'in the event that', replacement: 'if' },
  { phrase: 'in the near future', replacement: 'soon' },
  { phrase: 'with the exception of', replacement: 'except' },
  { phrase: 'due to the fact that', replacement: 'because' },
  { phrase: 'in spite of the fact that', replacement: 'although' },
  { phrase: 'for the purpose of', replacement: 'to' },
  { phrase: 'has the ability to', replacement: 'can' },
  { phrase: 'make a decision', replacement: 'decide' },
  { phrase: 'conduct an investigation', replacement: 'investigate' },
  { phrase: 'take into consideration', replacement: 'consider' },
  { phrase: 'reach a conclusion', replacement: 'conclude' },
  { phrase: 'provide assistance', replacement: 'help' },
  { phrase: 'make a recommendation', replacement: 'recommend' },
]

export const inflatedVocabulary: readonly PhraseEntry[] = [
  { phrase: 'utilize', replacement: 'use' },
  { phrase: 'utilizes', replacement: 'uses' },
  { phrase: 'utilized', replacement: 'used' },
  { phrase: 'utilizing', replacement: 'using' },
  { phrase: 'facilitate', replacement: 'help' },
  { phrase: 'facilitates', replacement: 'helps' },
  { phrase: 'facilitated', replacement: 'helped' },
  { phrase: 'facilitating', replacement: 'helping' },
  { phrase: 'ascertain', replacement: 'find out' },
  { phrase: 'ascertains', replacement: 'finds out' },
  { phrase: 'ascertained', replacement: 'found out' },
  { phrase: 'optimize', replacement: 'improve' },
  { phrase: 'optimizes', replacement: 'improves' },
  { phrase: 'optimized', replacement: 'improved' },
  { phrase: 'optimizing', replacement: 'improving' },
  { phrase: 'leverage', replacement: 'use' },
  { phrase: 'leverages', replacement: 'uses' },
  { phrase: 'leveraged', replacement: 'used' },
  { phrase: 'leveraging', replacement: 'using' },
  { phrase: 'endeavor', replacement: 'try' },
  { phrase: 'endeavors', replacement: 'tries' },
  { phrase: 'endeavored', replacement: 'tried' },
  { phrase: 'commence', replacement: 'start' },
  { phrase: 'commences', replacement: 'starts' },
  { phrase: 'commenced', replacement: 'started' },
  { phrase: 'commencing', replacement: 'starting' },
  { phrase: 'terminate', replacement: 'end' },
  { phrase: 'terminates', replacement: 'ends' },
  { phrase: 'terminated', replacement: 'ended' },
  { phrase: 'terminating', replacement: 'ending' },
  { phrase: 'regarding', replacement: 'about' },
  { phrase: 'subsequent', replacement: 'next' },
  { phrase: 'prior to', replacement: 'before' },
]

export const adverbWhitelist: ReadonlySet<string> = new Set([
  'only',
  'early',
  'likely',
  'family',
  'apply',
  'reply',
  'july',
  'supply',
  'daily',
  'weekly',
  'monthly',
  'friendly',
  'lovely',
  'lonely',
  'silly',
  'ugly',
  'holy',
  'ally',
  'jolly',
  'homely',
  'manly',
  'bully',
  'rally',
  'bubbly',
  'wobbly',
  'wiggly',
  'fly',
  'ply',
  'sly',
  'shy',
  'spy',
  'try',
  'cry',
  'dry',
  'fry',
  'pry',
  'sty',
  'italy',
  'sicily',
  'tally',
  'valley',
  'alley',
  'belly',
  'billy',
  'willy',
  'kelly',
  'molly',
  'polly',
  'wally',
  'wembley',
])

export const sentenceAbbreviations: ReadonlySet<string> = new Set([
  'mr.',
  'mrs.',
  'ms.',
  'dr.',
  'sr.',
  'jr.',
  'st.',
  'inc.',
  'co.',
  'ltd.',
  'corp.',
  'ph.d.',
  'm.d.',
  'b.a.',
  'm.a.',
  'e.g.',
  'i.e.',
  'etc.',
  'vs.',
  'cf.',
  'no.',
  'vol.',
  'ave.',
  'blvd.',
  'rd.',
  'apt.',
  'jan.',
  'feb.',
  'mar.',
  'apr.',
  'jun.',
  'jul.',
  'aug.',
  'sep.',
  'sept.',
  'oct.',
  'nov.',
  'dec.',
  'mon.',
  'tue.',
  'wed.',
  'thu.',
  'fri.',
  'sat.',
  'sun.',
  'a.m.',
  'p.m.',
  'u.s.',
  'u.k.',
  'u.n.',
  'e.u.',
  'u.s.a.',
])

export const bulletMarkers: readonly string[] = ['- ', '* ', '+ ', '• ', '– ', '— ', '‣ ', '· ']

export const passiveAuxiliaries: ReadonlySet<string> = new Set([
  'am',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'get',
  'gets',
  'got',
  'gotten',
  'getting',
])

export const irregularParticiples: ReadonlySet<string> = new Set([
  'been',
  'become',
  'begun',
  'bent',
  'born',
  'broken',
  'brought',
  'built',
  'bought',
  'burnt',
  'burst',
  'caught',
  'chosen',
  'come',
  'cost',
  'cut',
  'done',
  'drawn',
  'driven',
  'eaten',
  'fallen',
  'felt',
  'fought',
  'found',
  'given',
  'gone',
  'gotten',
  'had',
  'heard',
  'held',
  'hidden',
  'hit',
  'hurt',
  'kept',
  'known',
  'laid',
  'led',
  'left',
  'lent',
  'let',
  'lost',
  'made',
  'meant',
  'met',
  'paid',
  'put',
  'read',
  'run',
  'said',
  'seen',
  'sent',
  'set',
  'shaken',
  'shot',
  'shown',
  'shut',
  'slept',
  'sold',
  'sought',
  'spent',
  'spoken',
  'spread',
  'stood',
  'stuck',
  'sworn',
  'taken',
  'taught',
  'thought',
  'thrown',
  'told',
  'understood',
  'won',
  'written',
  'lit',
  'fit',
  'split',
  'torn',
  'worn',
  'fed',
  'bred',
  'shed',
  'sped',
  'bled',
  'fled',
  'wept',
  'swept',
  'flung',
  'frozen',
  'grown',
  'forgotten',
  'mistaken',
  'blown',
  'drawn',
  'risen',
  'sung',
  'sunk',
  'woven',
  'bound',
  'ground',
  'wound',
  'dug',
])

export const lyNonAdverbs: ReadonlySet<string> = new Set([
  'deadly',
  'costly',
  'timely',
  'lively',
  'kindly',
  'elderly',
  'orderly',
  'scholarly',
  'worldly',
  'leisurely',
  'hourly',
  'yearly',
  'cowardly',
  'measly',
  'gnarly',
  'assembly',
  'anomaly',
  'butterfly',
  'monopoly',
  'jelly',
  'lily',
  'folly',
  'rely',
  'imply',
  'comply',
  'multiply',
  'gravely',
  'panoply',
])

export const adjectivalPastParticiples: ReadonlySet<string> = new Set([
  'tired',
  'excited',
  'interested',
  'bored',
  'worried',
  'pleased',
  'satisfied',
  'surprised',
  'concerned',
  'confused',
  'scared',
  'frightened',
  'embarrassed',
  'married',
  'related',
  'located',
  'used',
  'supposed',
  'gifted',
  'talented',
  'dedicated',
  'committed',
  'qualified',
  'experienced',
  'detailed',
  'limited',
  'complicated',
  'sophisticated',
  'gone',
  'come',
  'become',
  'done',
  'grown',
  'risen',
  'fallen',
  'sunk',
])

export const passiveInterrupters: ReadonlySet<string> = new Set([
  'however',
  'therefore',
  'nonetheless',
  'nevertheless',
  'indeed',
  'of',
  'course',
  'after',
  'all',
])
