export interface PhraseEntry {
  readonly phrase: string
  readonly replacement?: string
}

export const fillers: readonly string[] = [
  'basically',
  'literally',
  'you know',
  'i mean',
  'just',
  'actually',
  'honestly',
  'obviously',
  'clearly',
  'right',
]

export const hedges: readonly string[] = [
  'kind of',
  'sort of',
  'a little bit',
  'maybe',
  'i think',
  'i feel like',
  'i guess',
  'perhaps',
  'somewhat',
  'slightly',
]

export const intensifiers: readonly string[] = [
  'very',
  'really',
  'extremely',
  'incredibly',
  'absolutely',
  'totally',
  'completely',
  'truly',
  'highly',
  'utterly',
]

export const redundantPairs: readonly string[] = [
  'absolutely essential',
  'completely finished',
  'very unique',
  'end result',
  'free gift',
  'past history',
  'future plans',
  'each and every',
  'first and foremost',
]

export const weaselAttribution: readonly string[] = [
  'some people say',
  'studies show',
  'experts agree',
  'research suggests',
]

export const selfAttribution: readonly string[] = [
  'i believe that',
  'in my opinion',
  'personally i think',
  'from my perspective',
]

export const credibilityKillers: readonly string[] = [
  'does that make sense',
  'if that makes sense',
]

export const weakClosers: readonly string[] = [
  'so yeah',
  'and stuff like that',
  'and whatnot',
  'you get the idea',
]

export const apologeticPreambles: readonly string[] = [
  'sorry but',
  'this might be wrong but',
  "i'm no expert but",
  "i'm not sure if this is right but",
]

export const throatClearing: readonly string[] = [
  "it's important to note that",
  'the fact of the matter is',
  'it goes without saying',
  'let me start by saying',
  'it should be noted that',
  'it is worth mentioning that',
  'needless to say',
  'as a matter of fact',
  'at the end of the day',
  'the bottom line is',
]

export const existenceStarters: readonly string[] = [
  'there is',
  'there are',
  'there was',
  'there will be',
]

export const frontLoadedNegatives: readonly string[] = [
  "i'm not sure",
  "i don't know if",
  "i can't say for certain",
]

export const wordyPhrases: readonly PhraseEntry[] = [
  { phrase: 'in order to', replacement: 'to' },
  { phrase: 'the reason being is', replacement: 'because' },
  { phrase: 'in the event that', replacement: 'if' },
  { phrase: 'in the near future', replacement: 'soon' },
  { phrase: 'with the exception of', replacement: 'except' },
  { phrase: 'due to the fact that', replacement: 'because' },
  { phrase: 'in spite of the fact that', replacement: 'although' },
  { phrase: 'for the purpose of', replacement: 'to' },
  { phrase: 'has the ability to', replacement: 'can' },
  { phrase: 'make a decision', replacement: 'decide' },
  { phrase: 'conduct an investigation', replacement: 'investigate' },
  { phrase: 'take into consideration', replacement: 'consider' },
  { phrase: 'reach a conclusion', replacement: 'conclude' },
  { phrase: 'provide assistance', replacement: 'help' },
  { phrase: 'make a recommendation', replacement: 'recommend' },
]

export const inflatedVocabulary: readonly PhraseEntry[] = [
  { phrase: 'utilize', replacement: 'use' },
  { phrase: 'utilizes', replacement: 'uses' },
  { phrase: 'utilized', replacement: 'used' },
  { phrase: 'utilizing', replacement: 'using' },
  { phrase: 'facilitate', replacement: 'help' },
  { phrase: 'facilitates', replacement: 'helps' },
  { phrase: 'facilitated', replacement: 'helped' },
  { phrase: 'facilitating', replacement: 'helping' },
  { phrase: 'ascertain', replacement: 'find out' },
  { phrase: 'ascertains', replacement: 'finds out' },
  { phrase: 'ascertained', replacement: 'found out' },
  { phrase: 'optimize', replacement: 'improve' },
  { phrase: 'optimizes', replacement: 'improves' },
  { phrase: 'optimized', replacement: 'improved' },
  { phrase: 'optimizing', replacement: 'improving' },
  { phrase: 'leverage', replacement: 'use' },
  { phrase: 'leverages', replacement: 'uses' },
  { phrase: 'leveraged', replacement: 'used' },
  { phrase: 'leveraging', replacement: 'using' },
  { phrase: 'endeavor', replacement: 'try' },
  { phrase: 'endeavors', replacement: 'tries' },
  { phrase: 'endeavored', replacement: 'tried' },
  { phrase: 'commence', replacement: 'start' },
  { phrase: 'commences', replacement: 'starts' },
  { phrase: 'commenced', replacement: 'started' },
  { phrase: 'commencing', replacement: 'starting' },
  { phrase: 'terminate', replacement: 'end' },
  { phrase: 'terminates', replacement: 'ends' },
  { phrase: 'terminated', replacement: 'ended' },
  { phrase: 'terminating', replacement: 'ending' },
  { phrase: 'regarding', replacement: 'about' },
  { phrase: 'subsequent', replacement: 'next' },
  { phrase: 'prior to', replacement: 'before' },
]

export const adverbWhitelist: ReadonlySet<string> = new Set([
  'only',
  'early',
  'likely',
  'family',
  'apply',
  'reply',
  'july',
  'supply',
  'daily',
  'weekly',
  'monthly',
  'friendly',
  'lovely',
  'lonely',
  'silly',
  'ugly',
  'holy',
  'ally',
  'jolly',
  'homely',
  'manly',
  'bully',
  'rally',
  'bubbly',
  'wobbly',
  'wiggly',
  'fly',
  'ply',
  'sly',
  'shy',
  'spy',
  'try',
  'cry',
  'dry',
  'fry',
  'pry',
  'sty',
  'italy',
  'sicily',
  'tally',
  'valley',
  'alley',
  'belly',
  'billy',
  'willy',
  'kelly',
  'molly',
  'polly',
  'wally',
  'wembley',
])

export const sentenceAbbreviations: ReadonlySet<string> = new Set([
  'mr.',
  'mrs.',
  'ms.',
  'dr.',
  'sr.',
  'jr.',
  'st.',
  'inc.',
  'co.',
  'ltd.',
  'corp.',
  'ph.d.',
  'm.d.',
  'b.a.',
  'm.a.',
  'e.g.',
  'i.e.',
  'etc.',
  'vs.',
  'cf.',
  'no.',
  'vol.',
  'ave.',
  'blvd.',
  'rd.',
  'apt.',
  'jan.',
  'feb.',
  'mar.',
  'apr.',
  'jun.',
  'jul.',
  'aug.',
  'sep.',
  'sept.',
  'oct.',
  'nov.',
  'dec.',
  'mon.',
  'tue.',
  'wed.',
  'thu.',
  'fri.',
  'sat.',
  'sun.',
  'a.m.',
  'p.m.',
  'u.s.',
  'u.k.',
  'u.n.',
  'e.u.',
  'u.s.a.',
])

export const bulletMarkers: readonly string[] = ['- ', '* ', '+ ', '• ', '– ', '— ', '‣ ', '· ']

export const passiveAuxiliaries: ReadonlySet<string> = new Set([
  'am',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'get',
  'gets',
  'got',
  'gotten',
  'getting',
])

export const irregularParticiples: ReadonlySet<string> = new Set([
  'been',
  'become',
  'begun',
  'bent',
  'born',
  'broken',
  'brought',
  'built',
  'bought',
  'burnt',
  'burst',
  'caught',
  'chosen',
  'come',
  'cost',
  'cut',
  'done',
  'drawn',
  'driven',
  'eaten',
  'fallen',
  'felt',
  'fought',
  'found',
  'given',
  'gone',
  'gotten',
  'had',
  'heard',
  'held',
  'hidden',
  'hit',
  'hurt',
  'kept',
  'known',
  'laid',
  'led',
  'left',
  'lent',
  'let',
  'lost',
  'made',
  'meant',
  'met',
  'paid',
  'put',
  'read',
  'run',
  'said',
  'seen',
  'sent',
  'set',
  'shaken',
  'shot',
  'shown',
  'shut',
  'slept',
  'sold',
  'sought',
  'spent',
  'spoken',
  'spread',
  'stood',
  'stuck',
  'sworn',
  'taken',
  'taught',
  'thought',
  'thrown',
  'told',
  'understood',
  'won',
  'written',
  'lit',
  'fit',
  'split',
  'torn',
  'worn',
  'fed',
  'bred',
  'shed',
  'sped',
  'bled',
  'fled',
  'wept',
  'swept',
  'flung',
  'frozen',
  'grown',
  'forgotten',
  'mistaken',
  'blown',
  'drawn',
  'risen',
  'sung',
  'sunk',
  'woven',
  'bound',
  'ground',
  'wound',
  'dug',
])

export const lyNonAdverbs: ReadonlySet<string> = new Set([
  'deadly',
  'costly',
  'timely',
  'lively',
  'kindly',
  'elderly',
  'orderly',
  'scholarly',
  'worldly',
  'leisurely',
  'hourly',
  'yearly',
  'cowardly',
  'measly',
  'gnarly',
  'assembly',
  'anomaly',
  'butterfly',
  'monopoly',
  'jelly',
  'lily',
  'folly',
  'rely',
  'imply',
  'comply',
  'multiply',
  'gravely',
  'panoply',
])

export const adjectivalPastParticiples: ReadonlySet<string> = new Set([
  'tired',
  'excited',
  'interested',
  'bored',
  'worried',
  'pleased',
  'satisfied',
  'surprised',
  'concerned',
  'confused',
  'scared',
  'frightened',
  'embarrassed',
  'married',
  'related',
  'located',
  'used',
  'supposed',
  'gifted',
  'talented',
  'dedicated',
  'committed',
  'qualified',
  'experienced',
  'detailed',
  'limited',
  'complicated',
  'sophisticated',
  'gone',
  'come',
  'become',
  'done',
  'grown',
  'risen',
  'fallen',
  'sunk',
])

export const passiveInterrupters: ReadonlySet<string> = new Set([
  'however',
  'therefore',
  'nonetheless',
  'nevertheless',
  'indeed',
  'of',
  'course',
  'after',
  'all',
])

export const subjectPronouns: ReadonlySet<string> = new Set([
  'i',
  'he',
  'she',
  'it',
  'we',
  'they',
  'you',
  'this',
  'that',
  'there',
])

export const finiteVerbs: ReadonlySet<string> = new Set([
  'is',
  'was',
  'are',
  'were',
  'am',
  'be',
  'has',
  'had',
  'have',
  'does',
  'did',
  'do',
  'can',
  'could',
  'will',
  'would',
  'should',
  'must',
  'may',
  'might',
  'shall',
  "isn't",
  "wasn't",
  "aren't",
  "weren't",
  "don't",
  "doesn't",
  "didn't",
  "can't",
  "won't",
  "couldn't",
  "wouldn't",
  "shouldn't",
  "hasn't",
  "haven't",
  "hadn't",
])

export const irregularPastTense: ReadonlySet<string> = new Set([
  'went',
  'came',
  'got',
  'took',
  'made',
  'said',
  'saw',
  'ran',
  'fell',
  'broke',
  'began',
  'knew',
  'grew',
  'threw',
  'flew',
  'drew',
  'gave',
  'drove',
  'rode',
  'rose',
  'wrote',
  'spoke',
  'chose',
  'froze',
  'woke',
  'sold',
  'told',
  'held',
  'stood',
  'found',
  'left',
  'felt',
  'kept',
  'slept',
  'meant',
  'sent',
  'spent',
  'built',
  'bought',
  'brought',
  'thought',
  'taught',
  'caught',
  'fought',
  'sought',
  'became',
  'forgot',
  'ate',
  'drank',
  'sang',
  'sank',
  'swam',
  'won',
  'lost',
  'met',
  'led',
  'read',
  'paid',
  'laid',
  'heard',
  'sat',
  'put',
  'let',
  'set',
])

export const coordinatingConjunctions: ReadonlySet<string> = new Set([
  'and',
  'but',
  'or',
  'nor',
  'for',
  'so',
  'yet',
])

export const conjunctiveAdverbs: ReadonlySet<string> = new Set([
  'however',
  'therefore',
  'then',
  'thus',
  'hence',
  'moreover',
  'otherwise',
  'meanwhile',
  'consequently',
  'instead',
  'still',
  'also',
  'besides',
  'furthermore',
  'nevertheless',
  'nonetheless',
])

export const clauseOpeners: ReadonlySet<string> = new Set([
  'when',
  'whenever',
  'if',
  'unless',
  'until',
  'till',
  'after',
  'before',
  'because',
  'since',
  'although',
  'though',
  'while',
  'once',
  'as',
  'where',
  'wherever',
  'whether',
  'by',
  'in',
  'on',
  'at',
  'for',
  'with',
  'without',
  'from',
  'to',
  'during',
  'despite',
  'given',
  'like',
  'near',
  'over',
  'under',
  'between',
  'among',
  'through',
  'throughout',
  'within',
  'across',
  'along',
  'around',
  'behind',
  'beyond',
  'considering',
  'regarding',
  'following',
  'amid',
  'per',
  'via',
  'of',
  'about',
  'above',
  'against',
  'even',
  'now',
])

export const placeholderNouns: readonly string[] = [
  'a way to',
  'a way of',
  'some way to',
  'something that',
  'something to',
  'a mechanism for',
  'a mechanism to',
  'the mechanism',
  'a mechanism',
  'this mechanism',
  'the thing that',
  'a means of',
  'a means to',
  'the approach',
  'this approach',
  'an approach',
  'the capability',
  'a capability',
  'this capability',
]

export const comparisonFrames: readonly string[] = [
  'is like',
  'are like',
  'think of it as',
  'think of this as',
  'imagine a',
  'imagine an',
  'imagine you',
  'akin to',
  'essentially a',
  'essentially an',
  'acts as a',
  'acts like',
  'works like',
  'behaves like',
  'as if it were',
  'is basically a',
]

export const ambiguousNecessityPhrases: readonly string[] = [
  'you need',
  'you will need',
  "you'll need",
  'we need',
  'needs to',
]

export const meansThatPhrases: readonly string[] = [
  'means that',
  'this means',
  'leads to',
  'leading to',
]

export const closingRestatements: readonly string[] = [
  'in summary',
  'in conclusion',
  'to recap',
  'to summarize',
  'to sum up',
  'overall',
]

export const authenticityWords: ReadonlySet<string> = new Set([
  'honest',
  'honestly',
  'genuine',
  'genuinely',
  'actual',
  'actually',
  'truly',
  'real',
])

export const authenticityWhitelist: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ['real', new Set(['number', 'numbers', 'time', 'world', 'estate', 'user', 'users', 'data', 'hardware', 'device', 'devices'])],
  ['actual', new Set(['parameter', 'parameters', 'argument', 'arguments', 'value', 'values', 'output', 'outputs', 'size', 'cost', 'behavior', 'behaviour'])],
])

export const emphasisFragments: ReadonlySet<string> = new Set([
  'it works',
  'it just works',
  "that's it",
  'that is it',
  "that's all",
  'that is all',
  "that's the whole point",
  'that is the whole point',
  "that's the point",
  'that is the point',
  'simple as that',
  'end of story',
  'full stop',
  'it matters',
  'this matters',
  "that's huge",
  'that is huge',
  'read that again',
])

export const nominalizations: ReadonlyMap<string, string> = new Map([
  ['validation', 'validate'],
  ['implementation', 'implement'],
  ['composition', 'compose'],
  ['configuration', 'configure'],
  ['convergence', 'converge'],
  ['declaration', 'declare'],
  ['optimization', 'optimize'],
  ['optimisation', 'optimise'],
  ['integration', 'integrate'],
  ['migration', 'migrate'],
  ['transformation', 'transform'],
  ['evaluation', 'evaluate'],
  ['verification', 'verify'],
  ['authentication', 'authenticate'],
  ['authorization', 'authorize'],
  ['initialization', 'initialize'],
  ['installation', 'install'],
  ['compilation', 'compile'],
  ['execution', 'execute'],
  ['deletion', 'delete'],
  ['creation', 'create'],
  ['generation', 'generate'],
  ['modification', 'modify'],
  ['notification', 'notify'],
  ['registration', 'register'],
  ['separation', 'separate'],
  ['comparison', 'compare'],
  ['assessment', 'assess'],
  ['measurement', 'measure'],
  ['improvement', 'improve'],
  ['management', 'manage'],
  ['handling', 'handle'],
  ['processing', 'process'],
  ['encryption', 'encrypt'],
  ['aggregation', 'aggregate'],
  ['normalization', 'normalize'],
  ['serialization', 'serialize'],
  ['translation', 'translate'],
  ['conversion', 'convert'],
  ['calculation', 'calculate'],
  ['determination', 'determine'],
  ['utilization', 'use'],
])

export const weakVerbs: ReadonlySet<string> = new Set([
  'do',
  'does',
  'did',
  'doing',
  'done',
  'make',
  'makes',
  'made',
  'making',
  'give',
  'gives',
  'gave',
  'given',
  'giving',
  'have',
  'has',
  'had',
  'having',
  'provide',
  'provides',
  'provided',
  'providing',
  'perform',
  'performs',
  'performed',
  'performing',
  'achieve',
  'achieves',
  'achieved',
  'achieving',
  'conduct',
  'conducts',
  'conducted',
  'conducting',
])

export const nominalInterveners: ReadonlySet<string> = new Set([
  'a',
  'an',
  'the',
  'its',
  'their',
  'our',
  'your',
  'this',
  'that',
  'some',
  'any',
  'full',
  'complete',
  'proper',
  'initial',
  'final',
])

export const acronymAllowlist: ReadonlySet<string> = new Set([
  'API', 'HTTP', 'HTTPS', 'URL', 'URI', 'CPU', 'GPU', 'RAM', 'ROM', 'SQL', 'JSON',
  'XML', 'HTML', 'CSS', 'JS', 'TS', 'ID', 'UID', 'UUID', 'PDF', 'CSV', 'TSV',
  'YAML', 'TOML', 'REST', 'RPC', 'CLI', 'GUI', 'UI', 'UX', 'SDK', 'IDE', 'TCP',
  'UDP', 'IP', 'DNS', 'TLS', 'SSL', 'SSH', 'JWT', 'CDN', 'DB', 'OS', 'IO', 'AI',
  'ML', 'LLM', 'US', 'UK', 'EU', 'USA', 'CEO', 'CTO', 'CFO', 'COO', 'VP', 'HR',
  'PR', 'FAQ', 'TV', 'PC', 'GB', 'MB', 'KB', 'TB', 'OK', 'AM', 'PM', 'USD',
  'EUR', 'GBP', 'II', 'III', 'IV', 'VI', 'VII', 'VIII', 'IX', 'XI', 'GDP', 'ISO',
  'IEEE', 'NASA', 'MIT', 'RSS', 'SEO', 'ROI', 'KPI', 'SLA', 'SSO', 'MFA', 'OTP',
  'DOM', 'RGB', 'PNG', 'JPG', 'JPEG', 'GIF', 'SVG', 'NLP', 'OCR', 'ETL', 'CRUD',
  'ACID', 'CORS', 'CSRF', 'XSS', 'AWS', 'GCP', 'IAM', 'VM', 'CI', 'CD', 'QA',
  'OAuth', 'iOS', 'macOS', 'GHz', 'MHz', 'kHz',
])

export const acronymIntroducers: ReadonlySet<string> = new Set(['called', 'named'])

export const synonymSets: readonly (readonly (readonly string[])[])[] = [
  [
    ['produce', 'produces', 'produced', 'producing'],
    ['emit', 'emits', 'emitted', 'emitting'],
    ['generate', 'generates', 'generated', 'generating'],
  ],
  [
    ['create', 'creates', 'created', 'creating'],
    ['instantiate', 'instantiates', 'instantiated', 'instantiating'],
  ],
  [
    ['show', 'shows', 'showed', 'shown', 'showing'],
    ['demonstrate', 'demonstrates', 'demonstrated', 'demonstrating'],
    ['illustrate', 'illustrates', 'illustrated', 'illustrating'],
  ],
  [
    ['require', 'requires', 'requiring'],
    ['necessitate', 'necessitates', 'necessitated', 'necessitating'],
  ],
  [
    ['use', 'uses', 'using'],
    ['leverage', 'leverages', 'leveraged', 'leveraging'],
    ['utilize', 'utilizes', 'utilized', 'utilizing', 'utilise', 'utilises', 'utilised', 'utilising'],
  ],
]

export const modalVerbs: ReadonlySet<string> = new Set(['can', 'cannot', 'could', 'may', 'might'])

export const pileBreakers: ReadonlySet<string> = new Set([
  'the',
  'a',
  'an',
  'this',
  'that',
  'these',
  'those',
  'its',
  'their',
  'our',
  'your',
  'my',
  'his',
  'her',
  'not',
  'no',
  'all',
  'both',
  'each',
  'every',
  'some',
  'any',
  'few',
  'many',
  'much',
  'more',
  'most',
  'several',
  'other',
  'another',
  'such',
  'own',
  'same',
  'very',
  'too',
  'also',
  'just',
  'only',
  'quite',
  'rather',
  'well',
  'who',
  'whom',
  'whose',
  'which',
  'what',
  'whether',
  'how',
  'why',
  'here',
  'then',
  'than',
  'one',
  'two',
  'three',
  'first',
  'second',
  'third',
  'last',
  'next',
  'new',
  'old',
])
